name: build-and-lint

# trigger: define when this workflow should run

on:
 workflow_dispatch:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: install backend dependencies
        working-directory: server
        run: npm ci

      - name: lint backend
        working-directory: server
        run: npm run lint -- --max-warnings=0

      - name: install frontend dependencies
        working-directory: client
        run: npm ci

      - name: lint frontend
        working-directory: client
        run: npm run lint -- --max-warnings=0

      - name: build backend image
        run: docker build -t backend ./server

      - name: build frontend image
        run: docker build -t frontend ./client